# Disclaimer: This code is for learning and research purposes only. Users should abide by the following principles:
# 1. Not for any commercial purposes.
# 2. When using, you should comply with the terms of use and robots.txt rules of the target platform.
# 3. Do not conduct large-scale crawling or cause operational interference to the platform.
# 4. The request frequency should be reasonably controlled to avoid unnecessary burden on the target platform.
# 5. May not be used for any illegal or inappropriate purposes.
#
# For detailed license terms, please refer to the LICENSE file in the project root directory.
# By using this code, you agree to abide by the above principles and all terms in LICENSE.

# -*- coding: utf-8 -*-
# @Author  : relakkes@gmail.com
# @Time    : 2024/1/14 17:34
# @Desc    :
from typing import List

import config
from var import source_keyword_var

from .xhs_store_media import *
from ._store_impl import *


class XhsStoreFactory:
    STORES = {
        "csv": XhsCsvStoreImplement,
        "db": XhsDbStoreImplement,
        "json": XhsJsonStoreImplement,
        "sqlite": XhsSqliteStoreImplement,
        "postgresql": XhsDbStoreImplement,
    }

    @staticmethod
    def create_store() -> AbstractStore:
        store_class = XhsStoreFactory.STORES.get(config.SAVE_DATA_OPTION)
        if not store_class:
            raise ValueError("[XhsStoreFactory.create_store] Invalid save option only supported csv or db or json or sqlite or postgresql ...")
        return store_class()


def get_video_url_arr(note_item: Dict) -> List:
    """Get video url array
    Args:
        note_item:

    Returns:"""
    if note_item.get('type') != 'video':
        return []

    videoArr = []
    originVideoKey = note_item.get('video').get('consumer').get('origin_video_key')
    if originVideoKey == '':
        originVideoKey = note_item.get('video').get('consumer').get('originVideoKey')
    # Downgrade with watermark
    if originVideoKey == '':
        videos = note_item.get('video').get('media').get('stream').get('h264')
        if type(videos).__name__ == 'list':
            videoArr = [v.get('master_url') for v in videos]
    else:
        videoArr = [f"http://sns-video-bd.xhscdn.com/{originVideoKey}"]

    return videoArr


async def update_xhs_note(note_item: Dict):
    """Update Xiaohongshu Notes
    Args:
        note_item:

    Returns:"""
    note_id = note_item.get("note_id")
    user_info = note_item.get("user", {})
    interact_info = note_item.get("interact_info", {})
    image_list: List[Dict] = note_item.get("image_list", [])
    tag_list: List[Dict] = note_item.get("tag_list", [])

    for img in image_list:
        if img.get('url_default') != '':
            img.update({'url': img.get('url_default')})

    video_url = ','.join(get_video_url_arr(note_item))

    local_db_item = {
        "note_id": note_item.get("note_id"),  # Post id
        "type": note_item.get("type"),  # Post type
        "title": note_item.get("title") or note_item.get("desc", "")[:255],  # Post title
        "desc": note_item.get("desc", ""),  # Post description
        "video_url": video_url,  # post video url
        "time": note_item.get("time"),  # Post publishing time
        "last_update_time": note_item.get("last_update_time", 0),  # Post last updated time
        "user_id": user_info.get("user_id"),  # user id
        "nickname": user_info.get("nickname"),  # User nickname
        "avatar": user_info.get("avatar"),  # User avatar
        "liked_count": interact_info.get("liked_count"),  # Number of likes
        "collected_count": interact_info.get("collected_count"),  # Number of collections
        "comment_count": interact_info.get("comment_count"),  # Number of comments
        "share_count": interact_info.get("share_count"),  # Number of shares
        "ip_location": note_item.get("ip_location", ""),  # IP address
        "image_list": ','.join([img.get('url', '') for img in image_list]),  # image url
        "tag_list": ','.join([tag.get('name', '') for tag in tag_list if tag.get('type') == 'topic']),  # Label
        "last_modify_ts": utils.get_current_timestamp(),  # Last update timestamp (generated by the MediaCrawler program, mainly used to record the latest update time of a record during db storage)
        "note_url": f"https://www.xiaohongshu.com/explore/{note_id}?xsec_token={note_item.get('xsec_token')}&xsec_source=pc_search",  # post url
        "source_keyword": source_keyword_var.get(),  # Search keywords
        "xsec_token": note_item.get("xsec_token"),  # xsec_token
    }
    utils.logger.info(f"[store.xhs.update_xhs_note] xhs note: {local_db_item}")
    await XhsStoreFactory.create_store().store_content(local_db_item)


async def batch_update_xhs_note_comments(note_id: str, comments: List[Dict]):
    """Batch update Xiaohongshu note comments
    Args:
        note_id:
        comments:

    Returns:"""
    if not comments:
        return
    for comment_item in comments:
        await update_xhs_note_comment(note_id, comment_item)


async def update_xhs_note_comment(note_id: str, comment_item: Dict):
    """Update Xiaohongshu Notes comments
    Args:
        note_id:
        comment_item:

    Returns:"""
    user_info = comment_item.get("user_info", {})
    comment_id = comment_item.get("id")
    comment_pictures = [item.get("url_default", "") for item in comment_item.get("pictures", [])]
    target_comment = comment_item.get("target_comment", {})
    local_db_item = {
        "comment_id": comment_id,  # comment id
        "create_time": comment_item.get("create_time"),  # Comment time
        "ip_location": comment_item.get("ip_location"),  # IP address
        "note_id": note_id,  # Post id
        "content": comment_item.get("content"),  # Comment content
        "user_id": user_info.get("user_id"),  # user id
        "nickname": user_info.get("nickname"),  # User nickname
        "avatar": user_info.get("image"),  # User avatar
        "sub_comment_count": comment_item.get("sub_comment_count", 0),  # Number of sub-comments
        "pictures": ",".join(comment_pictures),  # Comment on pictures
        "parent_comment_id": target_comment.get("id", 0),  # Parent comment id
        "last_modify_ts": utils.get_current_timestamp(),  # Last update timestamp (generated by the MediaCrawler program, mainly used to record the latest update time of a record during db storage)
        "like_count": comment_item.get("like_count", 0),
    }
    utils.logger.info(f"[store.xhs.update_xhs_note_comment] xhs note comment:{local_db_item}")
    await XhsStoreFactory.create_store().store_comment(local_db_item)


async def save_creator(user_id: str, creator: Dict):
    """Save Little Red Book Creator
    Args:
        user_id:
        creator:

    Returns:"""
    user_info = creator.get('basicInfo', {})

    follows = 0
    fans = 0
    interaction = 0
    for i in creator.get('interactions'):
        if i.get('type') == 'follows':
            follows = i.get('count')
        elif i.get('type') == 'fans':
            fans = i.get('count')
        elif i.get('type') == 'interaction':
            interaction = i.get('count')

    def get_gender(gender):
        if gender == 1:
            return '女'
        elif gender == 0:
            return '男'
        else:
            return None

    local_db_item = {
        'user_id': user_id,  # user id
        'nickname': user_info.get('nickname'),  # Nick name
        'gender': get_gender(user_info.get('gender')),  # gender
        'avatar': user_info.get('images'),  # avatar
        'desc': user_info.get('desc'),  # personal description
        'ip_location': user_info.get('ipLocation'),  # IP address
        'follows': follows,  # Number of followers
        'fans': fans,  # Number of fans
        'interaction': interaction,  # Number of interactions
        'tag_list': json.dumps({tag.get('tagType'): tag.get('name')
                                for tag in creator.get('tags')}, ensure_ascii=False),  # Label
        "last_modify_ts": utils.get_current_timestamp(),  # Last update timestamp (generated by the MediaCrawler program, mainly used to record the latest update time of a record during db storage)
    }
    utils.logger.info(f"[store.xhs.save_creator] creator:{local_db_item}")
    await XhsStoreFactory.create_store().store_creator(local_db_item)


async def update_xhs_note_image(note_id, pic_content, extension_file_name):
    """Update Xiaohongshu note pictures
    Args:
        note_id:
        pic_content:
        extension_file_name:

    Returns:"""

    await XiaoHongShuImage().store_image({"notice_id": note_id, "pic_content": pic_content, "extension_file_name": extension_file_name})


async def update_xhs_note_video(note_id, video_content, extension_file_name):
    """Update Xiaohongshu notes video
    Args:
        note_id:
        video_content:
        extension_file_name:

    Returns:"""

    await XiaoHongShuVideo().store_video({"notice_id": note_id, "video_content": video_content, "extension_file_name": extension_file_name})
